### ISSUE TITLE
scheduler caught exception:

### ISSUE THREAD

**Issue by capnayan** [mrichar1/dashing-sensu#6]
scheduler caught exception:
A JSON text must at least contain two octets!
/usr/lib/ruby/1.9.1/json/common.rb:148:in `initialize'
/usr/lib/ruby/1.9.1/json/common.rb:148:in `new'
/usr/lib/ruby/1.9.1/json/common.rb:148:in `parse'
/root/dashing-sensu/jobs/sensu.rb:36:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by mrichar1** [comment]
Please see #1 foe some probable causes of this.

Let me know if the problem continues after the sensu api etc has been checked.
